#!/usr/bin/env bash
set -e

TAG="$1"

if [ ! -e root.tar.xz ]; then
    curl -o root.tar.xz https://repo.voidlinux.eu/live/current/void-x86_64-ROOTFS-20171007.tar.xz
fi

if [ ! -e root-musl.tar.xz ]; then
    curl -o root-musl.tar.xz https://repo.voidlinux.eu/live/current/void-x86_64-musl-ROOTFS-20171007.tar.xz
fi

docker build --squash -t shizonic/void .
docker tag shizonic/void shizonic/void:$TAG

docker build --squash -f Dockerfile.musl -t shizonic/void-musl .
docker tag shizonic/void-musl shizonic/void-musl:$TAG
